### ISSUE TITLE
Binaries missing in 1.3.0 release

### ISSUE THREAD

**Issue by rvgud** [danielqsj/kafka_exporter#219] opened 2021-04-27 09:58 UTC
Can you please add the binaries in 1.3.0 release.

Thanks

**Comment by jonaz** [comment] 2021-04-28 13:23
Duplicate of https://github.com/danielqsj/kafka_exporter/issues/218

**Comment by karlism** [comment] 2021-05-18 06:45
Also duplicate of https://github.com/danielqsj/kafka_exporter/issues/211

**Comment by karlism** [comment] 2021-05-18 07:48
Appears to be fixed in 1.3.1.

**Comment by danielqsj** [comment] 2021-05-18 07:59
yes, I have fixed it in 1.3.1

**Closed by danielqsj** 2021-05-18 07:59 UTC

**Comment by karlism** [comment] 2021-05-18 08:01
Thanks!
